package com.pon4ikisdonut.elytrashahed;

enum MessageKey {
    ONLY_PLAYERS,
    NO_PERMISSION,
    SHAHED_ACTIVATED,
    SHAHED_DEACTIVATED,
    SHAHED_ALREADY_DISABLED,
    SHAHED_ACTIVATE_FAIL,
    SHAHED_POWER_SET,
    SHAHED_USAGE,
    AAGUN_RECEIVED,
    CONFIG_RELOADED,
    GHOST_USAGE,
    GHOST_RECEIVED,
    REACTIVE_ONLY_GLIDING,
    REACTIVE_TRIGGERED,
    NEED_TNT,
    SHAHED_DEATH_MESSAGE
}
